# Generated by Django 5.1.3 on 2024-11-12 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_student_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profileimage',
            field=models.ImageField(default='images/default_image.jpg', upload_to='profile-photo/'),
        ),
    ]
