# Generated by Django 5.1.3 on 2024-11-12 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_student_profileimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profileimage',
            field=models.ImageField(default='media/default_image.jpg.jpg', upload_to='media/profile_photos/'),
        ),
    ]
