# Generated by Django 5.1.3 on 2024-11-14 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_event_description_category_post_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='category',
            new_name='category_id',
        ),
    ]
