# Generated by Django 5.1.3 on 2024-11-16 04:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_post_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('profileimage', models.ImageField(default='media/default_image.jpg.jpg', upload_to='media/profile_photos/')),
                ('fullname', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('enroll_year', models.IntegerField()),
                ('current_GPA', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('department', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
