# Generated by Django 5.1.3 on 2024-11-16 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_profile_delete_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='student_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
